name: CI

on:
  push:
  pull_request:

jobs:
  unit-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Swift
        run: swift --version || true
      - name: Run unit tests
        run: swift test -v
  unit-linux-swift-61:
    runs-on: ubuntu-latest
    container:
      image: swift:6.1
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: swift test --scratch-path /tmp/swifter-build-6.1